version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app' # colon ':' present here and we create reference for the app container folder to present working directory locally
      - /usr/src/app/node_modules # no colon ':' in this command so we only mark this folde and use it from the container
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
